Document: jarvis
Title: Debian jarvis Manual
Author: <insert document author here>
Abstract: This manual describes what jarvis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jarvis/jarvis.sgml.gz

Format: postscript
Files: /usr/share/doc/jarvis/jarvis.ps.gz

Format: text
Files: /usr/share/doc/jarvis/jarvis.text.gz

Format: HTML
Index: /usr/share/doc/jarvis/html/index.html
Files: /usr/share/doc/jarvis/html/*.html
